#!/usr/bin/env python
import argparse
import io
from pathlib import Path
from urllib.request import urlopen
import sys
from zipfile import ZipFile


parser = argparse.ArgumentParser()
parser.add_argument(
    '--src', default='https://github.com/avelino/vim-bootstrap')
parser.add_argument(
    '--dest', default='files')


def get_github_download(url_base: str) -> str:
    return f"{url_base}/archive/master.zip"


def main(args):
    # Get current origin source (archive)
    target_dir = Path(args.dest).resolve()
    archive_url = get_github_download(args.src)
    resp = urlopen(archive_url)
    with ZipFile(io.BytesIO(resp.read())) as myzip:
        target_list = [
            name
            for name in myzip.namelist()
            if 'vim_template/langs/' in name][1:]
        for name in target_list:
            target = Path(name)
            if target.suffix == '':
                dest_dir = target_dir / target.name
                dest_dir.mkdir(exist_ok=True)
                continue
            dest_path = target_dir / '/'.join(target.parts[-2:])
            with dest_path.open('wb') as fp:
                fp.write(myzip.read(name))


if __name__ == '__main__':
    args = parser.parse_args()
    main(args)

